=== nbeaver/cmd-oysters/schemas/full-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "can-modify": {
      "type": "object",
      "properties": {
        "filesystem": {
          "type": "boolean"
        },
        "other-processes": {
          "type": "boolean"
        }
      },
      "additionalProperties": false
    },
    "component-command-info": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "bash-type": {
            "type": "string",
            "enum": [
              "builtin",
              "file",
              "keyword"
            ]
          },
          "debian": {
            "type": "object",
            "properties": {
              "executable-path": {
                "type": ["string", null]
              },
              "required-packages": {
                "type": "array",
                "items": {
                  "type": "string"
                },
                "additionalItems": false
              }
            },
            "additionalProperties": false
          },
          "requirements-in-general": {
            "type": "object",
            "properties": {
              "authentication": {
                "type": "string",
                "enum": [
                  "always",
                  "never",
                  "sometimes"
                ]
              },
              "internet-connection": {
                "type": "string",
                "enum": [
                  "always",
                  "never",
                  "sometimes"
                ]
              },
              "sudo": {
                "type": "string",
                "enum": [
                  "always",
                  "never",
                  "sometimes"
                ]
              }
            },
            "additionalProperties": false
          }
        },
        "additionalProperties": false
      }
    },
    "component-commands": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "copying": {
      "type": "object",
      "properties": {
        "authors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "license-name": {
          "type": "string"
        },
        "license-url": {
          "type": "string"
        },
        "year": {
          "type": "integer"
        }
      },
      "additionalProperties": false
    },
    "description": {
      "type": "object",
      "properties": {
        "nilsimsa-hex": {
          "type": "string"
        },
        "sha1-hex": {
          "type": "string"
        },
        "string": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "invocations": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "changeable-arguments": {
            "type": "object",
            "additionalProperties": {
              "type": "object",
              "properties": {
                "component-command": {
                  "type": "string"
                },
                "component-command-flag": {
                  "type": "string"
                },
                "description-string": {
                  "type": "string"
                },
                "invocation-slice": {
                  "type": "array",
                  "minItems": 2,
                  "maxItems": 2,
                  "items": [
                    {
                      "type": "integer"
                    },
                    {
                      "type": "integer"
                    }
                  ],
                  "additionalItems": false
                },
                "subtype": {
                  "type": "string"
                },
                "type": {
                  "type": "string",
                  "enum": [
                    "boolean",
                    "float",
                    "integer",
                    "string"
                  ]
                }
              },
              "additionalProperties": false
            }
          },
          "command-requirements-as-invoked": {
            "type": "object",
            "additionalProperties": {
              "type": "object",
              "properties": {
                "authentication": {
                  "type": "string",
                  "enum": [
                    "yes",
                    "no",
                    "maybe"
                  ]
                },
                "internet-connection": {
                  "type": "string",
                  "enum": [
                    "yes",
                    "no",
                    "maybe"
                  ]
                },
                "sudo": {
                  "type": "string",
                  "enum": [
                    "yes",
                    "no",
                    "maybe"
                  ]
                },
                "versions-tested": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  },
                  "additionalItems": false
                },
                "version-specifier": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          },
          "example-outputs": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "additionalItems": false
          },
          "nilsimsa-hex": {
            "type": "string"
          },
          "related-invocations": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "nilsimsa-hex": {
                  "type": "string"
                },
                "sha1-hex": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            },
            "additionalItems": false
          },
          "sha1-hex": {
            "type": "string"
          },
          "shell-compatibility": {
            "type": "object",
            "additionalProperties": {
              "type": "object",
              "properties": {
                "compatible-version-specifier": {
                  "type": "string"
                },
                "compatible-versions-tested": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  },
                  "additionalItems": false
                },
                "incompatible-version-specifier": {
                  "type": "string"
                },
                "incompatible-versions-tested": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  },
                  "additionalItems": false
                }
              },
              "additionalProperties": false
            }
          },
          "string": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "related-commands": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "nilsimsa-hex": {
            "type": "string"
          },
          "sha1-hex": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "relevant-urls": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "url-nilsimsa-hex": {
            "type": "string"
          },
          "url-sha1-hex": {
            "type": "string"
          },
          "url-string": {
            "type": "string"
          },
          "date-known-good": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "component-commands",
    "description",
    "invocations"
  ]
}

=== nbeaver/cmd-oysters/CmdOysters/040662df76d8e74369a2b56c10764ba16b44d2a7.json
{
    "can-modify": {
        "filesystem": true,
        "other-processes": false
    },
    "component-command-info": {
        "do": {
            "bash-type": "keyword"
        },
        "done": {
            "bash-type": "keyword"
        },
        "for": {
            "bash-type": "keyword"
        },
        "mkdir": {
            "bash-type": "file",
            "debian": {
                "executable-path": "/bin/mkdir",
                "required-packages": [
                    "coreutils"
                ]
            },
            "requirements-in-general": {
                "authentication": "never",
                "internet-connection": "never",
                "sudo": "sometimes"
            }
        },
        "pdfimages": {
            "bash-type": "file",
            "debian": {
                "executable-path": "/usr/bin/pdfimages",
                "required-packages": [
                    "poppler-utils"
                ]
            },
            "requirements-in-general": {
                "authentication": "never",
                "internet-connection": "never",
                "sudo": "sometimes"
            }
        }
    },
    "component-commands": [
        "do",
        "done",
        "for",
        "mkdir",
        "pdfimages"
    ],
    "copying": {
        "authors": [
            "Nathaniel Morck Beaver"
        ],
        "license-name": "MIT (Expat) License",
        "license-url": "http://opensource.org/licenses/MIT",
        "year": 2015
    },
    "description": {
        "nilsimsa-hex": "10b965aad81349edd7663a81e2b0979594cb293fd122f840578e2ef1f623ce2a",
        "sha1-hex": "040662df76d8e74369a2b56c10764ba16b44d2a7",
        "string": "For each file ending with '.pdf' in the current directory, extract the images from the pdf file into a new directory with the name of the file stripped of '.pdf'."
    },
    "invocations": {
        "bash": {
            "changeable-arguments": {
                "\"${f%.*}\"": {
                    "description-string": "Filename of PDF with '.pdf' stripped off. Used as the directory to store the images and image-root for image filenames.",
                    "invocation-slice": [
                        23,
                        32
                    ],
                    "subtype": "Shell expression that can be stored in a variable.",
                    "type": "string"
                }
            },
            "shell-compatibility": {
                "bash": {
                    "compatible-versions-tested": [
                        "4.2.37"
                    ]
                },
                "bsh": {
                    "compatible-versions-tested": [
                        "2.0b4"
                    ]
                },
                "csh": {
                    "incompatible-versions-tested": [
                        "20110502-2"
                    ]
                },
                "dash": {
                    "compatible-versions-tested": [
                        "0.5.7-3"
                    ]
                },
                "fish": {
                    "incompatible-versions-tested": [
                        "1.23.1"
                    ]
                },
                "ksh": {
                    "compatible-versions-tested": [
                        "93u+-1.2"
                    ]
                },
                "mksh": {
                    "compatible-versions-tested": [
                       "40.9.20120630-7"
                    ]
                },
                "posh": {
                    "compatible-versions-tested": [
                        "0.10.2"
                    ]
                },
                "tcsh": {
                    "incompatible-versions-tested": [
                        "6.18.01 (Astron) 2012-02-14"
                    ]
                },
                "zsh": {
                    "compatible-versions-tested": [
                        "4.3.17"
                    ]
                }
            },
            "nilsimsa-hex": "b287705fc40a710595646eda32e76b609dd82a885a74afe40f82d0c46a75f23e",
            "sha1-hex": "69eb231e93a2ec3f9ad6fdbcfede4fba0cbe6b15",
            "string": "for f in *.pdf; do dir=\"${f%.*}\"; mkdir -p \"$dir\" && pdfimages -j \"$f\" \"$dir/$dir\"; done"
        }
    }
}
