=== nbeaver/cmd-oysters/schemas/full-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "can-modify": {
      "type": "object",
      "properties": {
        "filesystem": {
          "type": "boolean"
        },
        "other-processes": {
          "type": "boolean"
        }
      },
      "additionalProperties": false
    },
    "component-command-info": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "bash-type": {
            "type": "string",
            "enum": [
              "builtin",
              "file",
              "keyword"
            ]
          },
          "debian": {
            "type": "object",
            "properties": {
              "executable-path": {
                "type": ["string", null]
              },
              "required-packages": {
                "type": "array",
                "items": {
                  "type": "string"
                },
                "additionalItems": false
              }
            },
            "additionalProperties": false
          },
          "requirements-in-general": {
            "type": "object",
            "properties": {
              "authentication": {
                "type": "string",
                "enum": [
                  "always",
                  "never",
                  "sometimes"
                ]
              },
              "internet-connection": {
                "type": "string",
                "enum": [
                  "always",
                  "never",
                  "sometimes"
                ]
              },
              "sudo": {
                "type": "string",
                "enum": [
                  "always",
                  "never",
                  "sometimes"
                ]
              }
            },
            "additionalProperties": false
          }
        },
        "additionalProperties": false
      }
    },
    "component-commands": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "copying": {
      "type": "object",
      "properties": {
        "authors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "license-name": {
          "type": "string"
        },
        "license-url": {
          "type": "string"
        },
        "year": {
          "type": "integer"
        }
      },
      "additionalProperties": false
    },
    "description": {
      "type": "object",
      "properties": {
        "nilsimsa-hex": {
          "type": "string"
        },
        "sha1-hex": {
          "type": "string"
        },
        "string": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "invocations": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "changeable-arguments": {
            "type": "object",
            "additionalProperties": {
              "type": "object",
              "properties": {
                "component-command": {
                  "type": "string"
                },
                "component-command-flag": {
                  "type": "string"
                },
                "description-string": {
                  "type": "string"
                },
                "invocation-slice": {
                  "type": "array",
                  "minItems": 2,
                  "maxItems": 2,
                  "items": [
                    {
                      "type": "integer"
                    },
                    {
                      "type": "integer"
                    }
                  ],
                  "additionalItems": false
                },
                "subtype": {
                  "type": "string"
                },
                "type": {
                  "type": "string",
                  "enum": [
                    "boolean",
                    "float",
                    "integer",
                    "string"
                  ]
                }
              },
              "additionalProperties": false
            }
          },
          "command-requirements-as-invoked": {
            "type": "object",
            "additionalProperties": {
              "type": "object",
              "properties": {
                "authentication": {
                  "type": "string",
                  "enum": [
                    "yes",
                    "no",
                    "maybe"
                  ]
                },
                "internet-connection": {
                  "type": "string",
                  "enum": [
                    "yes",
                    "no",
                    "maybe"
                  ]
                },
                "sudo": {
                  "type": "string",
                  "enum": [
                    "yes",
                    "no",
                    "maybe"
                  ]
                },
                "versions-tested": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  },
                  "additionalItems": false
                },
                "version-specifier": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          },
          "example-outputs": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "additionalItems": false
          },
          "nilsimsa-hex": {
            "type": "string"
          },
          "related-invocations": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "nilsimsa-hex": {
                  "type": "string"
                },
                "sha1-hex": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            },
            "additionalItems": false
          },
          "sha1-hex": {
            "type": "string"
          },
          "shell-compatibility": {
            "type": "object",
            "additionalProperties": {
              "type": "object",
              "properties": {
                "compatible-version-specifier": {
                  "type": "string"
                },
                "compatible-versions-tested": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  },
                  "additionalItems": false
                },
                "incompatible-version-specifier": {
                  "type": "string"
                },
                "incompatible-versions-tested": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  },
                  "additionalItems": false
                }
              },
              "additionalProperties": false
            }
          },
          "string": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "related-commands": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "nilsimsa-hex": {
            "type": "string"
          },
          "sha1-hex": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "relevant-urls": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "url-nilsimsa-hex": {
            "type": "string"
          },
          "url-sha1-hex": {
            "type": "string"
          },
          "url-string": {
            "type": "string"
          },
          "date-known-good": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "component-commands",
    "description",
    "invocations"
  ]
}

=== nbeaver/cmd-oysters/CmdOysters/10fb1d782f10eb50f61349f4a2973362319ebb87.json
{
    "can-modify": {
        "filesystem": true,
        "other-processes": false
    },
    "component-commands": [
        "gzip"
    ],
    "copying": {
        "authors": [
            "Nathaniel Morck Beaver"
        ],
        "license-name": "MIT (Expat) License",
        "license-url": "http://opensource.org/licenses/MIT",
        "year": 2015
    },
    "description": {
        "nilsimsa-hex": "f3bb12e916c3da561476a7d1e4bcf322a46549b729728218cbbfdc13b26cfe1c",
        "sha1-hex": "10fb1d782f10eb50f61349f4a2973362319ebb87",
        "string": "Compress a file using gzip without removing the original file."
    },
    "invocations": {
        "POSIX": {
            "changeable-arguments": {
                "file": {
                    "description-string": "Path to file to be compressed.",
                    "invocation-slice": [
                        7,
                        11
                    ],
                    "subtype": "File path.",
                    "type": "string"
                },
                "file.gz": {
                    "description-string": "Path to output compressed file.",
                    "invocation-slice": [
                        14,
                        21
                    ],
                    "subtype": "File path.",
                    "type": "string"
                }
            },
            "nilsimsa-hex": "5a152601aa9184185074c3c020603b2228c568030b2a10083276aa09b6367b4e",
            "sha1-hex": "f5b9d9dd13a9e49a65f0f455be0666a96229a049",
            "string": "gzip < file > file.gz"
        },
        "POSIX-recent-version": {
            "command-requirements-as-invoked": {
                "gzip": {
                    "version-specifier": "1.6 or later"
                }
            },
            "nilsimsa-hex": "1b000a105900100011148190a26212200006c20010d242052112002126105b2c",
            "sha1-hex": "d0ae2509d0086c92567e0183864d95be97f50f17",
            "string": "gzip -k file"
        },
        "POSIX-recent-version-long-flags": {
            "command-requirements-as-invoked": {
                "gzip": {
                    "version-specifier": "1.6 or later"
                }
            },
            "nilsimsa-hex": "3b002ab822202f105d10298cb0a113250004c34981e20280603a1003a611782c",
            "sha1-hex": "f521f470f90f4811c2d0ca70741d3254ce4eee6f",
            "string": "gzip --keep file"
        }
    },
    "relevant-urls": [
        {
            "date-known-good": "2015-05-12",
            "url-nilsimsa-hex": "60d8f3ab3231fbdaa3de37f1f0105eb5f990f96a9f16b1fa4f95f77f59a1d9af",
            "url-sha1-hex": "c8b54a257cdc941e26c282136042b33c277d996d",
            "url-string": "https://lists.gnu.org/archive/html/info-gnu/2013-06/msg00003.html"
        },
        {
            "date-known-good": "2015-05-12",
            "url-nilsimsa-hex": "bdd7a9a382a17b906ac0bf2651bc22f12789f84d396c32e6cc68d803e4ba594a",
            "url-sha1-hex": "b1bd2ff86405b81ffc9f21a877fe14c8fbfd659b",
            "url-string": "https://unix.stackexchange.com/questions/46786/how-to-tell-gzip-to-keep-original-file"
        },
        {
            "date-known-good": "2015-05-12",
            "url-nilsimsa-hex": "bac6aae2b78f324dbf30c1a3e4791f086760da587c8024b63195302324cf4aa3",
            "url-sha1-hex": "f9a888df7613ab538ce16e51ad8659aca3793b61",
            "url-string": "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=240539"
        }
    ]
}

=== nbeaver/cmd-oysters/CmdOysters/324aa3ea7d1c5fa22bab543daaf98435473c61cb.json
{
    "can-modify": {
        "filesystem": false,
        "other-processes": false
    },
    "component-command-info": {
        "xset": {
            "bash-type": "file",
            "debian": {
                "executable-path": "/usr/bin/xset",
                "required-packages": [
                    "x11-xserver-utils"
                ]
            },
            "requirements-in-general": {
                "authentication": "never",
                "internet-connection": "never",
                "sudo": "never"
            }
        }
    },
    "component-commands": [
        "xset"
    ],
    "description": {
        "nilsimsa-hex": "37b401c9104ca8a5cb98b0f898a4a4f10d093fe951ac046c280d861c731824e8",
        "sha1-hex": "324aa3ea7d1c5fa22bab543daaf98435473c61cb",
        "string": "Turn off the monitor; make the display go dark; blank the screen until the mouse is moved or a key is pressed."
    },
    "copying": {
        "authors": [
            "Nathaniel Morck Beaver"
        ],
        "license-name": "MIT (Expat) License",
        "license-url": "http://opensource.org/licenses/MIT",
        "year": 2015
    },
    "invocations": {
        "POSIX": {
            "nilsimsa-hex": "8374e121c48c68c95f74590404c5446692e20d19f5fa514977662ab1aca71809",
            "sha1-hex": "cc1938fb35ff47f16a237a9c6cd68add2aa6f4fd",
            "string": "xset dpms force standby"
        }
    },
    "relevant-urls": [
        {
            "url-nilsimsa-hex": "cca60bb3e68ce4fc2ff236ab4feebca8678565efadf82343aeddc27e269b2c32",
            "url-sha1-hex": "15d213217a71ca0b74987214297ffc96e0af5acb",
            "url-string": "http://magnatecha.com/turn-off-display-from-linux-command-line/",
            "date-known-good": "2015-04-30"
        },
        {
            "url-nilsimsa-hex": "bddeffea8ddbb1b59453eda6db0aecc2fd9bc7d51cf61fbeb77fcefaef77afb0",
            "url-sha1-hex": "e9b86330e870109f0ef0fb11dca4d18d68f55f89",
            "url-string": "http://superuser.com/a/66923/219809",
            "date-known-good": "2015-04-30"
        },
        {
            "url-nilsimsa-hex": "59aae1319110c40fd613a6a61d732fa929c623baa8d0ab4008f9284f228505ca",
            "url-sha1-hex": "11a35de5b6c3367fb96afdffb3e2aa5de9a777ff",
            "url-string": "http://www.cyberciti.biz/faq/linux-how-to-find-if-processor-is-64-bit-or-not/",
            "date-known-good": "2015-04-30"
        },
        {
            "url-nilsimsa-hex": "bfe8bfe9f0769bfb7c6772622f679050ef4b660c4c8c511f6000d87f4a419211",
            "url-sha1-hex": "01581fa9e93b91f5b8a7c1391e949b7deb777ae2",
            "url-string": "http://tldp.org/HOWTO/Battery-Powered/methods.html#XF86",
            "date-known-good": "2015-04-30"
        },
        {
            "url-nilsimsa-hex": "f15355b0acdab1b9bee5bb94066670806b0b4f845f1322a25f7a86d4fd3fb23f",
            "url-sha1-hex": "65279d37ecefc250d0ec50d609b6ae711062eb61",
            "url-string": "https://wiki.archlinux.org/index.php/Display_Power_Management_Signaling#Modifying_DPMS_and_screensaver_settings_using_xset",
            "date-known-good": "2015-04-30"
        }
    ]
}

=== nbeaver/cmd-oysters/CmdOysters/2e1ca763ebea072b02b583a7a91af95abfacf31f.json
{
    "can-modify": {
        "filesystem": true,
        "other-processes": false
    },
    "component-command-info": {
        "xclip": {
            "bash-type": "file",
            "debian": {
                "executable-path": "/usr/bin/xclip",
                "required-packages": [
                    "xclip"
                ]
            },
            "requirements-in-general": {
                "authentication": "never",
                "internet-connection": "never",
                "sudo": "never"
            }
        }
    },
    "component-commands": [
        "xclip"
    ],
    "copying": {
        "authors": [
            "Nathaniel Morck Beaver"
        ],
        "license-name": "MIT (Expat) License",
        "license-url": "http://opensource.org/licenses/MIT",
        "year": 2015
    },
    "description": {
        "nilsimsa-hex": "ceb939785d208b4e6c17c5e96df232342ae5a898fa0ab70c2336914543936c68",
        "sha1-hex": "2e1ca763ebea072b02b583a7a91af95abfacf31f",
        "string": "Save copied image to file."
    },
    "invocations": {
        "POSIX": {
            "changeable-arguments": {
                "out.png": {
                    "component-command": "xclip",
                    "description-string": "Filename of image.",
                    "invocation-slice": [
                        45,
                        52
                    ],
                    "subtype": "Path to image filename.",
                    "type": "string"
                }
            },
            "nilsimsa-hex": "a5cfff9ac40b8024850c784b85eb24090a820dd5aad0c72228f18eed6b1ad1e7",
            "sha1-hex": "e44dd9a6721b775889264363cbfa49d7c3dd6fda",
            "string": "xclip -selection clipboard -t image/png -o > out.png"
        },
        "POSIX-long-flags": {
            "changeable-arguments": {
                "out.png": {
                    "component-command": "xclip",
                    "description-string": "Filename of image.",
                    "invocation-slice": [
                        52,
                        59
                    ],
                    "subtype": "Path to image filename.",
                    "type": "string"
                }
            },
            "nilsimsa-hex": "a7cf7f9af70bab24879c6c4985ef744d0ae23acd8ad2c76768188aed5b1ed1e7",
            "sha1-hex": "331cbf7a000cea9d941670504c916d1bf7f197b3",
            "string": "xclip -selection clipboard -target image/png -out > out.png"
        }
    },
    "relevant-urls": [
        {
            "url-nilsimsa-hex": "",
            "url-sha1-hex": "",
            "url-string": "http://unix.stackexchange.com/questions/145131/copy-image-from-clipboard-to-file",
            "date-known-good": "2015-04-30"
        },
        {
            "url-nilsimsa-hex": "",
            "url-sha1-hex": "",
            "url-string": "http://ubuntuforums.org/showthread.php?t=1335075",
            "date-known-good": "2015-04-30"
        }
    ]
}

=== nbeaver/cmd-oysters/CmdOysters/118f2d8f8666f09b5d9c9db536d645be5f923f6c.json
{
    "can-modify": {
        "filesystem": false,
        "other-processes": false
    },
    "component-command-info": {
        "grep": {
            "bash-type": "file",
            "debian": {
                "executable-path": "/bin/grep",
                "required-packages": [
                    "grep"
                ]
            },
            "requirements-in-general": {
                "authentication": "sometimes",
                "internet-connection": "never",
                "sudo": "sometimes"
            }
        },
        "less": {
            "bash-type": "file",
            "debian": {
                "executable-path": "/usr/bin/less",
                "required-packages": [
                    "less"
                ]
            },
            "requirements-in-general": {
                "authentication": "sometimes",
                "internet-connection": "never",
                "sudo": "sometimes"
            }
        }
    },
    "component-commands": [
        "grep",
        "less"
    ],
    "copying": {
        "authors": [
            "Nathaniel Morck Beaver"
        ],
        "license-name": "MIT (Expat) License",
        "license-url": "http://opensource.org/licenses/MIT",
        "year": 2015
    },
    "description": {
        "nilsimsa-hex": "3efcd29b3a75e43c4748e7b9e8a87dbd3c5700739963c6a7b7169fd3de9477ef",
        "sha1-hex": "118f2d8f8666f09b5d9c9db536d645be5f923f6c",
        "string": "Highlight non-ASCII characters (e.g. Unicode) in a text file and give the line number they are on."
    },
    "invocations": {
        "POSIX": {
            "changeable-arguments": {
                "myfile.txt": {
                    "component-command": "grep",
                    "description-string": "File or file path of text file.",
                    "invocation-slice": [
                        39,
                        49
                    ],
                    "subtype": "path",
                    "type": "string"
                }
            },
            "nilsimsa-hex": "da8f7868256c22fcd1fcec9e9420ff1b662e8c915d8a0749e0f878503658e048",
            "sha1-hex": "8f78d31acfe82ec49214053d40ad2c338a9b51aa",
            "shell-compatibility": {
                "bash": {
                    "compatible-versions-tested": [
                        "4.2.37"
                    ]
                },
                "bsh": {
                    "incompatible-versions-tested": [
                        "2.0b4"
                    ]
                },
                "csh": {
                    "compatible-versions-tested": [
                        "20110502"
                    ]
                },
                "dash": {
                    "compatible-versions-tested": [
                        "0.5.7"
                    ]
                },
                "fish": {
                    "compatible-versions-tested": [
                        "1.23.1"
                    ]
                },
                "ksh": {
                    "compatible-versions-tested": [
                        "93u+-1.2"
                    ]
                },
                "mksh": {
                    "compatible-versions-tested": [
                       "40.9.20120630"
                    ]
                },
                "posh": {
                    "compatible-versions-tested": [
                        "0.10.2"
                    ]
                },
                "tcsh": {
                    "compatible-versions-tested": [
                        "6.18.01 (Astron) 2012-02-14"
                    ]
                },
                "zsh": {
                    "compatible-versions-tested": [
                        "4.3.17"
                    ]
                }
            },
            "string": "grep -nP '[^[:ascii:]]' --color=always myfile.txt | less -R"
        },
        "POSIX-long-flags": {
            "changeable-arguments": {
                "myfile.txt": {
                    "component-command": "grep",
                    "description-string": "File or file path of text file.",
                    "invocation-slice": [
                        63,
                        73
                    ],
                    "subtype": "path",
                    "type": "string"
                }
            },
            "nilsimsa-hex": "f8c2d869056620e65268ac8a1020381b44260413fd882749c0787890365880ec",
            "sha1-hex": "c2fe383b7f8e87e5baa638b3f4f074ad2f057614",
            "shell-compatibility": {
                "bash": {
                    "compatible-versions-tested": [
                        "4.2.37"
                    ]
                },
                "bsh": {
                    "incompatible-versions-tested": [
                        "2.0b4"
                    ]
                },
                "csh": {
                    "compatible-versions-tested": [
                        "20110502"
                    ]
                },
                "dash": {
                    "compatible-versions-tested": [
                        "0.5.7"
                    ]
                },
                "fish": {
                    "compatible-versions-tested": [
                        "1.23.1"
                    ]
                },
                "ksh": {
                    "compatible-versions-tested": [
                        "93u+-1.2"
                    ]
                },
                "mksh": {
                    "compatible-versions-tested": [
                       "40.9.20120630"
                    ]
                },
                "posh": {
                    "compatible-versions-tested": [
                        "0.10.2"
                    ]
                },
                "tcsh": {
                    "compatible-versions-tested": [
                        "6.18.01 (Astron) 2012-02-14"
                    ]
                },
                "zsh": {
                    "compatible-versions-tested": [
                        "4.3.17"
                    ]
                }
            },
            "string": "grep --line-number --perl-regexp '[^[:ascii:]]' --color=always myfile.txt | less --RAW-CONTROL-CHARS"
        }
    },
    "relevant-urls": [
        {
            "url-nilsimsa-hex": "4080bb110211f908a31e0270f1001604e0d061483414a9aa4c41e07d0309082f",
            "url-sha1-hex": "fd24214c7a8d4188f9201cb5366da312b98cd918",
            "url-string": "http://lists.gnu.org/archive/html/bug-gnu-utils/2006-03/msg00000.html",
            "date-known-good": "2015-04-30"
        },
        {
            "url-nilsimsa-hex": "5a000d0a34b4645c5280a1b96340686a47d17aed39170266102ca28a4c208002",
            "url-sha1-hex": "378313cfb8ae9abe444d304d4d7b4904641719a4",
            "url-string": "https://groups.google.com/forum/#!topic/comp.unix.programmer/Auge3Bz4iCA",
            "date-known-good": "2015-04-30"
        },
        {
            "url-nilsimsa-hex": "b8f9b409479163d62fe8edf2d19c32838db97db51da61cc7630fbbef2cff11eb",
            "url-sha1-hex": "af012f8aeffe8b95af828877e98196ec60e04a8a",
            "url-string": "https://stackoverflow.com/questions/3001177/how-do-i-grep-for-all-non-ascii-characters-in-unix",
            "date-known-good": "2015-04-30"
        },
        {
            "url-nilsimsa-hex": "b9d8bf9d0503671608f9b9bec39828832818ded5d8ea9787620fc3a22f0638e7",
            "url-sha1-hex": "0cc81af19f9953b0b808bd42b001419602609394",
            "url-string": "http://superuser.com/questions/417305/how-can-i-identify-non-ascii-characters-from-the-shell",
            "date-known-good": "2015-04-30"
        }
    ]
}

=== nbeaver/cmd-oysters/CmdOysters/c3248866c4ec72d23e3912e1589e1781fd9b92e5.json
{
    "can-modify": {
        "filesystem": false,
        "other-processes": false
    },
    "component-command-info": {
        "find": {
            "bash-type": "file",
            "debian": {
                "executable-path": "/usr/bin/find",
                "required-packages": [
                    "findutils"
                ]
            },
            "requirements-in-general": {
                "authentication": "never",
                "internet-connection": "never",
                "sudo": "sometimes"
            }
        }
    },
    "component-commands": [
        "find"
    ],
    "copying": {
        "authors": [
            "Nathaniel Morck Beaver"
        ],
        "license-name": "MIT (Expat) License",
        "license-url": "http://opensource.org/licenses/MIT",
        "year": 2015
    },
    "description": {
        "nilsimsa-hex": "9e74cd22f0d68ce48ff7128166a01fa9139bbe845907d36c76472ae5a91229b1",
        "sha1-hex": "c3248866c4ec72d23e3912e1589e1781fd9b92e5",
        "string": "Find files in your home directory that you don't own."
    },
    "invocations": {
        "POSIX": {
            "changeable-arguments": {
                "$HOME": {
                    "component-command": "find",
                    "description-string": "Path to search.",
                    "invocation-slice": [
                        5,
                        10
                    ],
                    "subtype": "Path to file or directory.",
                    "type": "string"
                },
                "$USER": {
                    "component-command": "find",
                    "component-command-flag": "-user",
                    "description-string": "User login the file is not owned by.",
                    "invocation-slice": [
                        19,
                        24
                    ],
                    "subtype": "Login user name.",
                    "type": "string"
                }
            },
            "nilsimsa-hex": "a5274945a6b08943c1c52b882d9121e005b9185cbb325c3fbbc39e54e63f3788",
            "sha1-hex": "1648be79c2a5b366c37d0ec72d20736fcbf5566d",
            "string": "find $HOME ! -user $USER"
        }
    }
}
